using System.Text.RegularExpressions;

namespace SentinelBridge.Core.Models;

internal static partial class GenetecEventSpanishLocalizer
{
    private static readonly IReadOnlyDictionary<string, string> ExactNames =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["AlarmAcknowledged"] = "Alarma reconocida",
            ["AlarmAcknowledgedAlternate"] = "Reconocimiento alternativo de alarma",
            ["AlarmInvestigating"] = "Alarma en investigación",
            ["AlarmConditionCleared"] = "Condición de alarma restablecida",
            ["AlarmContextChanged"] = "Contexto de alarma modificado",
            ["AlarmForciblyAcked"] = "Alarma reconocida de forma forzada",
            ["AlarmTriggered"] = "Alarma activada",
            ["ArchivingStartedByAlarm"] = "Grabación iniciada por alarma",
            ["ArchivingStoppedByAlarm"] = "Grabación detenida por alarma",
            ["AreaDuressPinEntered"] = "PIN de coacción introducido en el área",
            ["ExternalSystemAlarmTriggered"] = "Alarma de sistema externo activada",
            ["ZoneGlassBreak"] = "Rotura de vidrio detectada",
            ["InputAlarmActive"] = "Alarma de entrada activada",
            ["InputAlarmRestored"] = "Alarma de entrada restablecida",
            ["AccessGranted"] = "Acceso concedido",
            ["AccessRefused"] = "Acceso denegado",
            ["AccessUnknownCredential"] = "Acceso denegado: credencial desconocida",
            ["AccessExpiredCredential"] = "Acceso denegado: credencial vencida",
            ["AccessStolenCredential"] = "Acceso denegado: credencial robada",
            ["AccessInvalidPin"] = "Acceso denegado: PIN inválido",
            ["AccessAntipassbackViolation"] = "Acceso denegado: violación de antipassback",
            ["DoorOpen"] = "Puerta abierta",
            ["DoorClose"] = "Puerta cerrada",
            ["DoorOpenedForTooLong"] = "Puerta abierta durante demasiado tiempo",
            ["DoorOpenWhileLockSecure"] = "Puerta abierta mientras estaba asegurada",
            ["DoorForcedOpen"] = "Puerta forzada",
            ["CameraSignalLost"] = "Señal de cámara perdida",
            ["CameraSignalRecovered"] = "Señal de cámara recuperada",
            ["CameraTransmissionLost"] = "Transmisión de cámara perdida",
            ["CameraTransmissionRecovered"] = "Transmisión de cámara recuperada",
            ["HealthMonitoringEventConnectionFailed"] = "Monitoreo de salud: conexión fallida",
            ["HealthMonitoringEventConnectionRestored"] = "Monitoreo de salud: conexión restablecida",
            ["HealthMonitoringEventDatabaseLost"] = "Monitoreo de salud: base de datos perdida",
            ["HealthMonitoringEventDatabaseRecovered"] = "Monitoreo de salud: base de datos recuperada",
            ["HealthMonitoringEventEntityOffline"] = "Monitoreo de salud: entidad fuera de línea",
            ["HealthMonitoringEventEntityOnline"] = "Monitoreo de salud: entidad en línea"
        };

    private static readonly (string Prefix, string Translation)[] Prefixes =
    [
        ("HealthMonitoringEvent", "Monitoreo de salud"),
        ("HealthMonitoringEven", "Monitoreo de salud"),
        ("HealthMonitoring", "Monitoreo de salud"),
        ("AccessControlUnit", "Unidad de control de acceso"),
        ("VideoAnalytics", "Analítica de video"),
        ("IntrusionArea", "Área de intrusión"),
        ("IntrusionUnit", "Unidad de intrusión"),
        ("ParkingSession", "Sesión de estacionamiento"),
        ("ParkingZone", "Zona de estacionamiento"),
        ("EmergencyDoor", "Puerta de emergencia"),
        ("Cardholder", "Tarjetahabiente"),
        ("Credential", "Credencial"),
        ("Archiver", "Archivador"),
        ("Application", "Aplicación"),
        ("Directory", "Directorio"),
        ("Camera", "Cámara"),
        ("Door", "Puerta"),
        ("Elevator", "Ascensor"),
        ("Interface", "Interfaz"),
        ("Patroller", "Patrullero"),
        ("Unit", "Unidad"),
        ("Area", "Área"),
        ("Zone", "Zona"),
        ("Lpr", "LPR")
    ];

    private static readonly IReadOnlyDictionary<string, string> Words =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["Access"] = "acceso",
            ["Acknowledged"] = "reconocida",
            ["Action"] = "acción",
            ["Active"] = "activa",
            ["Activated"] = "activada",
            ["Added"] = "agregado",
            ["Agent"] = "agente",
            ["Alarm"] = "alarma",
            ["Alarms"] = "alarmas",
            ["All"] = "todos",
            ["Alternate"] = "alternativo",
            ["Analytics"] = "analítica",
            ["Antipassback"] = "antipassback",
            ["Application"] = "aplicación",
            ["Archive"] = "archivo",
            ["Archiver"] = "archivador",
            ["Archiving"] = "grabación",
            ["Area"] = "área",
            ["Armed"] = "armada",
            ["Arming"] = "armado",
            ["Assumed"] = "asumida",
            ["Asset"] = "activo",
            ["Assigned"] = "asignada",
            ["Automatic"] = "automática",
            ["Automation"] = "automatización",
            ["Backup"] = "respaldo",
            ["Badge"] = "tarjeta",
            ["Battery"] = "batería",
            ["Before"] = "antes",
            ["Biometric"] = "biométrica",
            ["Block"] = "bloqueo",
            ["By"] = "por",
            ["Bypass"] = "anulación",
            ["Call"] = "llamada",
            ["Camera"] = "cámara",
            ["Cancelled"] = "cancelada",
            ["Canceled"] = "cancelada",
            ["Card"] = "tarjeta",
            ["Cardholder"] = "tarjetahabiente",
            ["Certificate"] = "certificado",
            ["Changed"] = "modificado",
            ["Check"] = "verificación",
            ["Closed"] = "cerrada",
            ["Close"] = "cerrar",
            ["Cloud"] = "nube",
            ["Completed"] = "completada",
            ["Communications"] = "comunicaciones",
            ["Condition"] = "condición",
            ["Confirmation"] = "confirmación",
            ["Connected"] = "conectada",
            ["Connection"] = "conexión",
            ["Consolidation"] = "consolidación",
            ["Contact"] = "contacto",
            ["Context"] = "contexto",
            ["Convenience"] = "cortesía",
            ["Count"] = "conteo",
            ["CPU"] = "CPU",
            ["Credential"] = "credencial",
            ["Critical"] = "crítica",
            ["Custom"] = "personalizado",
            ["Database"] = "base de datos",
            ["Dead"] = "muerto",
            ["Deactivated"] = "desactivada",
            ["Deleted"] = "eliminado",
            ["Denied"] = "denegado",
            ["Detected"] = "detectado",
            ["Detection"] = "detección",
            ["Directory"] = "directorio",
            ["Disabled"] = "deshabilitada",
            ["Disarmed"] = "desarmada",
            ["Disconnected"] = "desconectada",
            ["Disk"] = "disco",
            ["Double"] = "doble",
            ["Driver"] = "controlador",
            ["Drift"] = "desfase",
            ["Duress"] = "coacción",
            ["Edge"] = "borde",
            ["Edgestorage"] = "almacenamiento en borde",
            ["Elevator"] = "ascensor",
            ["Emergency"] = "emergencia",
            ["Ended"] = "finalizada",
            ["Entered"] = "introducido",
            ["Entity"] = "entidad",
            ["Entry"] = "entrada",
            ["Error"] = "error",
            ["Escort"] = "escolta",
            ["Event"] = "evento",
            ["Exceeded"] = "excedido",
            ["Exited"] = "salida",
            ["Expired"] = "vencida",
            ["External"] = "externo",
            ["Fail"] = "falla",
            ["Failed"] = "fallida",
            ["Failure"] = "falla",
            ["Failover"] = "conmutación por error",
            ["File"] = "archivo",
            ["Files"] = "archivos",
            ["Firmware"] = "firmware",
            ["Free"] = "libre",
            ["Full"] = "lleno",
            ["Glass"] = "vidrio",
            ["Grant"] = "concesión",
            ["Granted"] = "concedido",
            ["Grace"] = "gracia",
            ["Health"] = "salud",
            ["High"] = "alto",
            ["Hit"] = "coincidencia",
            ["Inactive"] = "inactiva",
            ["In"] = "en",
            ["Input"] = "entrada",
            ["Interface"] = "interfaz",
            ["Intrusion"] = "intrusión",
            ["Invalid"] = "inválida",
            ["Identity"] = "identidad",
            ["License"] = "matrícula",
            ["Live"] = "en vivo",
            ["Lock"] = "bloqueo",
            ["Locked"] = "bloqueada",
            ["Lockdown"] = "confinamiento",
            ["Locking"] = "bloqueo",
            ["Loss"] = "pérdida",
            ["Lost"] = "perdida",
            ["Low"] = "bajo",
            ["Macro"] = "macro",
            ["Maintenance"] = "mantenimiento",
            ["Manual"] = "manual",
            ["Manually"] = "manualmente",
            ["Many"] = "múltiples",
            ["Master"] = "principal",
            ["Max"] = "máximo",
            ["Media"] = "medios",
            ["Memory"] = "memoria",
            ["Missing"] = "ausente",
            ["Mode"] = "modo",
            ["Monitored"] = "monitoreada",
            ["Monitoring"] = "monitoreo",
            ["Motion"] = "movimiento",
            ["Multiple"] = "múltiple",
            ["No"] = "sin",
            ["Normal"] = "normal",
            ["Not"] = "no",
            ["Object"] = "objeto",
            ["Occupancy"] = "ocupación",
            ["Off"] = "desactivada",
            ["Offline"] = "fuera de línea",
            ["Offload"] = "descarga",
            ["On"] = "activada",
            ["Online"] = "en línea",
            ["Open"] = "abierta",
            ["Operator"] = "operador",
            ["Optimized"] = "optimizado",
            ["Override"] = "anulación",
            ["Pack"] = "paquete",
            ["Packet"] = "paquete",
            ["Paid"] = "pagado",
            ["Parking"] = "estacionamiento",
            ["Partial"] = "parcial",
            ["Patroller"] = "patrullero",
            ["People"] = "personas",
            ["Perimeter"] = "perimetral",
            ["Period"] = "período",
            ["Person"] = "persona",
            ["Pin"] = "PIN",
            ["Plate"] = "matrícula",
            ["POS"] = "POS",
            ["Postponed"] = "pospuesta",
            ["Presence"] = "presencia",
            ["Problem"] = "problema",
            ["Protection"] = "protección",
            ["Ptz"] = "PTZ",
            ["Read"] = "lectura",
            ["Reached"] = "alcanzado",
            ["Recorded"] = "grabada",
            ["Recording"] = "grabación",
            ["Recovered"] = "recuperada",
            ["Registered"] = "registrado",
            ["Request"] = "solicitud",
            ["Requested"] = "solicitada",
            ["Required"] = "requerida",
            ["Reset"] = "restablecimiento",
            ["Response"] = "respuesta",
            ["Restore"] = "restauración",
            ["Restored"] = "restablecida",
            ["Rex"] = "solicitud de salida",
            ["Role"] = "rol",
            ["Rtp"] = "RTP",
            ["Rule"] = "regla",
            ["Sas"] = "SAS",
            ["Schedule"] = "programación",
            ["Scheduled"] = "programada",
            ["Sc"] = "Security Center",
            ["Secured"] = "asegurada",
            ["Service"] = "servicio",
            ["Session"] = "sesión",
            ["Signal"] = "señal",
            ["Single"] = "única",
            ["Source"] = "origen",
            ["Space"] = "espacio",
            ["Start"] = "inicio",
            ["Started"] = "iniciada",
            ["Startup"] = "inicio",
            ["State"] = "estado",
            ["Stolen"] = "robada",
            ["Stop"] = "detención",
            ["Stopped"] = "detenida",
            ["Storage"] = "almacenamiento",
            ["Streaming"] = "transmisión",
            ["Success"] = "exitosa",
            ["Succeeded"] = "exitosa",
            ["Supervisor"] = "supervisor",
            ["Synchronization"] = "sincronización",
            ["System"] = "sistema",
            ["Tamper"] = "sabotaje",
            ["Temperature"] = "temperatura",
            ["Test"] = "prueba",
            ["Threshold"] = "umbral",
            ["Time"] = "tiempo",
            ["Timeout"] = "tiempo de espera",
            ["Token"] = "token",
            ["Too"] = "demasiado",
            ["Transmission"] = "transmisión",
            ["Threat"] = "amenaza",
            ["Trickling"] = "transferencia gradual",
            ["Trouble"] = "problema",
            ["Triggered"] = "activada",
            ["Unauthorized"] = "no autorizado",
            ["Unexpectedly"] = "inesperadamente",
            ["Unit"] = "unidad",
            ["Unknown"] = "desconocida",
            ["Unlocked"] = "desbloqueada",
            ["Unlock"] = "desbloqueo",
            ["Unregistered"] = "no registrado",
            ["Update"] = "actualización",
            ["Upgrade"] = "actualización",
            ["Upload"] = "carga",
            ["Usage"] = "uso",
            ["User"] = "usuario",
            ["Valid"] = "válida",
            ["Validating"] = "validando",
            ["Validation"] = "validación",
            ["Vehicle"] = "vehículo",
            ["Video"] = "video",
            ["Violation"] = "violación",
            ["Visitor"] = "visitante",
            ["Vrm"] = "VRM",
            ["Warning"] = "advertencia",
            ["Window"] = "ventana",
            ["With"] = "con",
            ["Write"] = "escritura",
            ["Zone"] = "zona",
            ["Zoom"] = "zoom",
            ["AC"] = "CA",
            ["Lpr"] = "LPR",
            ["Abnormal"] = "anormal",
            ["Aborted"] = "abortada",
            ["Absent"] = "ausente",
            ["Acked"] = "reconocida",
            ["Adaptive"] = "adaptativa",
            ["And"] = "y",
            ["Answered"] = "respondida",
            ["APB"] = "APB",
            ["Arm"] = "armado",
            ["Astray"] = "extraviado",
            ["Attempt"] = "intento",
            ["Audio"] = "audio",
            ["Auth"] = "autenticación",
            ["Auto"] = "automático",
            ["Automatically"] = "automáticamente",
            ["Bat"] = "batería",
            ["Because"] = "debido a",
            ["Below"] = "por debajo de",
            ["Bolt"] = "cerrojo",
            ["Bookmark"] = "marcador",
            ["Break"] = "rotura",
            ["Button"] = "botón",
            ["Bwc"] = "cámara corporal",
            ["Bypassed"] = "anulada",
            ["Can"] = "puede",
            ["Cancel"] = "cancelación",
            ["Capacity"] = "capacidad",
            ["Change"] = "cambio",
            ["Cleared"] = "restablecida",
            ["Command"] = "comando",
            ["Companion"] = "acompañante",
            ["Complete"] = "completa",
            ["Config"] = "configuración",
            ["Counting"] = "conteo",
            ["Credentiallost"] = "credencial perdida",
            ["Crossed"] = "cruzó",
            ["Crowd"] = "multitud",
            ["Declined"] = "rechazada",
            ["Delay"] = "retraso",
            ["Despite"] = "a pesar de",
            ["Direction"] = "dirección",
            ["Disarm"] = "desarmado",
            ["Door"] = "puerta",
            ["Edited"] = "editado",
            ["Enabled"] = "habilitada",
            ["Encryption"] = "cifrado",
            ["Enforced"] = "aplicada",
            ["Established"] = "establecida",
            ["Evacuation"] = "evacuación",
            ["Execute"] = "ejecución",
            ["Expiring"] = "por vencer",
            ["Extension"] = "extensión",
            ["Face"] = "rostro",
            ["Failuret"] = "falla",
            ["Fall"] = "caída",
            ["Field"] = "campo",
            ["First"] = "primera",
            ["Flooding"] = "saturación",
            ["Floor"] = "piso",
            ["Following"] = "siguiente",
            ["For"] = "para",
            ["Forced"] = "forzada",
            ["Forcibly"] = "forzosamente",
            ["Forgiven"] = "perdonada",
            ["Formatted"] = "formateado",
            ["Fusion"] = "fusión",
            ["Guard"] = "guardia",
            ["Has"] = "tiene",
            ["Heat"] = "calor",
            ["Host"] = "servidor",
            ["Hotlist"] = "lista de interés",
            ["Ignored"] = "ignorada",
            ["Imported"] = "importada",
            ["Inplace"] = "en posición",
            ["Installed"] = "instalada",
            ["Installing"] = "instalando",
            ["Insufficient"] = "insuficiente",
            ["Interlock"] = "interbloqueo",
            ["Invalidate"] = "invalidar",
            ["Inventory"] = "inventario",
            ["Investigating"] = "investigación",
            ["Invite"] = "invitación",
            ["Is"] = "está",
            ["Key"] = "clave",
            ["Knob"] = "perilla",
            ["Last"] = "última",
            ["Left"] = "izquierda",
            ["Level"] = "nivel",
            ["Line"] = "línea",
            ["Load"] = "carga",
            ["Logged"] = "sesión",
            ["Login"] = "inicio de sesión",
            ["Loitering"] = "merodeo",
            ["Long"] = "prolongado",
            ["Man"] = "persona",
            ["Map"] = "mapa",
            ["Match"] = "coincidencia",
            ["Maximum"] = "máximo",
            ["Merged"] = "fusionado",
            ["Mismatch"] = "discrepancia",
            ["Mixed"] = "mixto",
            ["Mlpi"] = "MLPI",
            ["Modifiedincident"] = "incidente modificado",
            ["Mounted"] = "montado",
            ["Moved"] = "movido",
            ["Mustering"] = "reunión",
            ["Nominal"] = "nominal",
            ["None"] = "ninguno",
            ["Of"] = "de",
            ["Old"] = "antigua",
            ["One"] = "uno",
            ["Opened"] = "abierta",
            ["Out"] = "fuera",
            ["Outof"] = "fuera de",
            ["Package"] = "paquete",
            ["Packets"] = "paquetes",
            ["Passage"] = "paso",
            ["Path"] = "ruta",
            ["Permit"] = "permiso",
            ["Physical"] = "físico",
            ["Playback"] = "reproducción",
            ["Point"] = "punto",
            ["Privileges"] = "privilegios",
            ["Process"] = "proceso",
            ["Published"] = "publicada",
            ["Pull"] = "tirador",
            ["Queue"] = "cola",
            ["Reader"] = "lector",
            ["Reading"] = "lectura",
            ["Reads"] = "lecturas",
            ["Recognized"] = "reconocido",
            ["Reconnected"] = "reconectada",
            ["Record"] = "registro",
            ["Recovery"] = "recuperación",
            ["Reentered"] = "reingreso",
            ["Refused"] = "denegado",
            ["Rejected"] = "rechazada",
            ["Release"] = "liberación",
            ["Released"] = "liberada",
            ["Relock"] = "volver a bloquear",
            ["Remote"] = "remoto",
            ["Removed"] = "eliminado",
            ["Replacement"] = "reemplazo",
            ["Restarted"] = "reiniciada",
            ["Result"] = "resultado",
            ["Results"] = "resultados",
            ["Retention"] = "retención",
            ["Retry"] = "reintento",
            ["Ringing"] = "timbrando",
            ["Rotated"] = "girada",
            ["Route"] = "ruta",
            ["Run"] = "ejecución",
            ["Second"] = "segunda",
            ["Secret"] = "secreto",
            ["Secure"] = "seguro",
            ["Sensor"] = "sensor",
            ["Sent"] = "enviado",
            ["Sequence"] = "secuencia",
            ["Server"] = "servidor",
            ["Sessio"] = "sesión",
            ["Settings"] = "configuración",
            ["Shared"] = "compartido",
            ["Short"] = "cortocircuito",
            ["Shunted"] = "derivada",
            ["Sight"] = "vista",
            ["Silenced"] = "silenciada",
            ["Size"] = "tamaño",
            ["Slide"] = "deslizamiento",
            ["Specified"] = "especificado",
            ["Split"] = "dividida",
            ["SSO"] = "SSO",
            ["Station"] = "estación",
            ["Supported"] = "compatible",
            ["Synchronizationpartially"] = "sincronización parcial",
            ["Tail"] = "cola",
            ["Tailgating"] = "seguimiento no autorizado",
            ["Tampering"] = "manipulación",
            ["To"] = "a",
            ["Transfer"] = "transferencia",
            ["Transferred"] = "transferida",
            ["Trunk"] = "troncal",
            ["Un"] = "no",
            ["Unassigned"] = "no asignada",
            ["Undefined"] = "indefinida",
            ["Uninstalled"] = "desinstalada",
            ["Uninstalling"] = "desinstalando",
            ["Unlocking"] = "desbloqueando",
            ["Unmounted"] = "desmontado",
            ["Unsecured"] = "no asegurada",
            ["Unshunted"] = "sin derivación",
            ["Unsupported"] = "no compatible",
            ["Updated"] = "actualizada",
            ["Uploaded"] = "cargada",
            ["Vehicled"] = "vehículo",
            ["Velocity"] = "velocidad",
            ["Walkthrough"] = "paso",
            ["Warnin"] = "advertencia",
            ["While"] = "mientras"
        };

    internal static string Translate(string eventTypeId)
    {
        if (ExactNames.TryGetValue(eventTypeId, out var exact)) return exact;

        var prefix = Prefixes.FirstOrDefault(item =>
            eventTypeId.StartsWith(item.Prefix, StringComparison.OrdinalIgnoreCase));
        var remainder = string.IsNullOrEmpty(prefix.Prefix)
            ? eventTypeId
            : eventTypeId[prefix.Prefix.Length..];
        var translatedRemainder = TranslateWords(remainder);

        if (string.IsNullOrWhiteSpace(prefix.Translation)) return UppercaseFirst(translatedRemainder);
        return string.IsNullOrWhiteSpace(translatedRemainder)
            ? prefix.Translation
            : $"{prefix.Translation}: {translatedRemainder}";
    }

    private static string TranslateWords(string value)
    {
        var tokens = IdentifierTokenRegex().Matches(value)
            .Select(match => match.Value)
            .Where(token => !token.Equals("Event", StringComparison.OrdinalIgnoreCase))
            .Select(token => Words.TryGetValue(token, out var translated) ? translated : token);
        return UppercaseFirst(string.Join(' ', tokens));
    }

    private static string UppercaseFirst(string value) => string.IsNullOrWhiteSpace(value)
        ? string.Empty
        : char.ToUpperInvariant(value[0]) + value[1..];

    [GeneratedRegex(@"[A-Z]+(?=[A-Z][a-z]|\d|$)|[A-Z]?[a-z]+|\d+")]
    private static partial Regex IdentifierTokenRegex();
}

